// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Q2Kpxp-7EisAvzFKpsXqxuGbnk73nQA',
    appId: '1:217432727337:web:cd261a6bec30347cb66138',
    messagingSenderId: '217432727337',
    projectId: 'beautymaster-c9035',
    authDomain: 'beautymaster-c9035.firebaseapp.com',
    storageBucket: 'beautymaster-c9035.appspot.com',
    measurementId: 'G-C86KHLT90Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwi1frEBoa6yfUz7GpAx67ElBR0jSsnr4',
    appId: '1:217432727337:android:edc4c74e74a64f01b66138',
    messagingSenderId: '217432727337',
    projectId: 'beautymaster-c9035',
    storageBucket: 'beautymaster-c9035.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMkfhJD9xHbidxo-lAixtRlge3IHyllVA',
    appId: '1:217432727337:ios:320baf827e017383b66138',
    messagingSenderId: '217432727337',
    projectId: 'beautymaster-c9035',
    storageBucket: 'beautymaster-c9035.appspot.com',
    iosBundleId: 'com.example.beautymaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMkfhJD9xHbidxo-lAixtRlge3IHyllVA',
    appId: '1:217432727337:ios:320baf827e017383b66138',
    messagingSenderId: '217432727337',
    projectId: 'beautymaster-c9035',
    storageBucket: 'beautymaster-c9035.appspot.com',
    iosBundleId: 'com.example.beautymaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_Q2Kpxp-7EisAvzFKpsXqxuGbnk73nQA',
    appId: '1:217432727337:web:907f026a251ceeb5b66138',
    messagingSenderId: '217432727337',
    projectId: 'beautymaster-c9035',
    authDomain: 'beautymaster-c9035.firebaseapp.com',
    storageBucket: 'beautymaster-c9035.appspot.com',
    measurementId: 'G-5XSVCNXEDP',
  );
}
